name: PHP

on:
  pull_request:
  push:
    branches:
      - master
env:
  DATABASE_URL: mysql://root@127.0.0.1:33306/su_news_test?serverVersion=5.7

jobs:
  test:
    name: 'PHP ${{ matrix.php-version }} (${{ matrix.dependency-versions }}, Lint ${{ matrix.lint }})'
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - php-version: '8.0'
            lint: false
            coverage: false
            dependency-versions: 'highest'
            tools: 'composer:v2'
            env:
              SYMFONY_DEPRECATIONS_HELPER: weak

          - php-version: '8.1'
            lint: false
            coverage: false
            dependency-versions: 'highest'
            tools: 'composer:v2'
            env:
              SYMFONY_DEPRECATIONS_HELPER: weak

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Install and configure PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: ctype, iconv, mysql
          coverage: pcov
          tools: ${{ matrix.tools }}

      - name: Install composer dependencies
        uses: ramsey/composer-install@v1
        with:
          dependency-versions: ${{ matrix.dependency-versions }}
          composer-options: ${{ matrix.composer-options }}

      - name: bootstrap test environment
        run: composer bootstrap-test-environment

      - name: Run unit tests
        run: composer phpunit -- Tests/Unit --coverage-php var/coverage.php --coverage-html coverage-report --log-junit var/junit.xml